// Numerical-parity tests against the Python mlx-vis reference.
//
// Fixtures are generated by tools/gen_fixtures.py from the Python package and
// bundled as a test resource (Fixtures/parity.json). Only DETERMINISTIC stages
// are compared here — these are the shared-core building blocks every method
// depends on. Stochastic embeddings can't bit-match across RNGs and are covered
// by the shape/NaN tests in CoreTests.

import Foundation
import MLX
import XCTest

import MLXVis

private struct Fixture: Decodable {
    let n: Int
    let d: Int
    let k: Int
    let X: [Float]
    let knn_indices: [Int32]
    let knn_dists: [Float]
    let knn_dists_sq: [Float]
    let pca2: [Float]
    let norm_standard: [Float]
    let norm_minmax: [Float]
    let ab: [Float]
    let fft_n: Int
    let fft_Y: [Float]
    let fft_Z: Float
    let fft_grad: [Float]
}

final class ParityTests: XCTestCase {
    private var fx: Fixture!

    override func setUpWithError() throws {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "parity", withExtension: "json"),
            "parity.json fixture not found in test bundle")
        fx = try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    private var inputX: MLXArray {
        MLXArray(fx.X, [fx.n, fx.d])
    }

    /// Max absolute elementwise difference between an MLXArray and a flat reference.
    private func maxAbsDiff(_ a: MLXArray, _ ref: [Float]) -> Float {
        let flat = a.reshaped([-1]).asArray(Float.self)
        precondition(flat.count == ref.count, "size mismatch \(flat.count) vs \(ref.count)")
        var m: Float = 0
        for i in 0..<flat.count { m = Swift.max(m, abs(flat[i] - ref[i])) }
        return m
    }

    // MARK: normalize

    func testNormalizeStandardParity() {
        let y = normalizeInput(inputX, method: .standard)
        XCTAssertLessThan(maxAbsDiff(y, fx.norm_standard), 1e-4)
    }

    func testNormalizeMinMaxParity() {
        let y = normalizeInput(inputX, method: .minmax)
        XCTAssertLessThan(maxAbsDiff(y, fx.norm_minmax), 1e-4)
    }

    // MARK: find a,b params

    func testFindABParity() {
        let (a, b) = UMAP.findABParams(spread: 1.0, minDist: 0.1)
        XCTAssertEqual(a, fx.ab[0], accuracy: 1e-3)
        XCTAssertEqual(b, fx.ab[1], accuracy: 1e-3)
    }

    // MARK: brute-force KNN (exact)

    func testBruteForceKNNParity() {
        let (idx, dist) = bruteForceKNN(inputX, k: fx.k, returnEuclidean: true)
        // Distances must match closely.
        XCTAssertLessThan(maxAbsDiff(dist, fx.knn_dists), 1e-3)

        // Indices: exact match per neighbor (random float input → no ties).
        let swiftIdx = idx.reshaped([-1]).asArray(Int32.self)
        var mism = 0
        for i in 0..<swiftIdx.count where swiftIdx[i] != fx.knn_indices[i] { mism += 1 }
        XCTAssertEqual(mism, 0, "\(mism)/\(swiftIdx.count) KNN indices differ from reference")
    }

    func testBruteForceKNNSquaredParity() {
        let (_, dist) = bruteForceKNN(inputX, k: fx.k, returnEuclidean: false)
        XCTAssertLessThan(maxAbsDiff(dist, fx.knn_dists_sq), 1e-2)
    }

    // MARK: PCA (compared via the sign/rotation-invariant pairwise-distance matrix)

    func testPCAParity() {
        let swiftY = PCA(nComponents: 2).fitTransform(inputX)
        let pyY = MLXArray(fx.pca2, [fx.n, 2])

        // SVD-vs-eigh differ by per-axis sign, so compare the pairwise distance
        // matrices, which are invariant to sign flips and orthogonal rotations of
        // the (identical) top-2 principal subspace.
        func pdist(_ y: MLXArray) -> MLXArray {
            let sq = (y * y).sum(axis: 1)
            return maximum(
                sq.expandedDimensions(axis: 1) + sq.expandedDimensions(axis: 0)
                    - 2.0 * y.matmul(y.transposed()), 0.0)
        }
        let dPy = pdist(pyY)
        // Relative max error against the distance scale (these are squared distances,
        // O(100+) for the fixture's spectrum, so an absolute tolerance would be
        // mis-scaled). ~1e-4 relative is float32-level agreement.
        let absDiff = abs(pdist(swiftY) - dPy).max().item(Float.self)
        let scale = dPy.max().item(Float.self)
        let rel = absDiff / scale
        XCTAssertLessThan(rel, 1e-3, "PCA pairwise-distance relative mismatch: \(rel)")
    }

    // MARK: FFT repulsive (Swift port vs Python reference, identical input)

    func testFFTRepulsiveParity() {
        let y = MLXArray(fx.fft_Y, [fx.fft_n, 2])
        let (z, grad) = fftRepulsiveGrad(y, n: fx.fft_n)

        // Same libmlx FFT on both sides → expect tight agreement.
        let zRel = abs(z.item(Float.self) - fx.fft_Z) / abs(fx.fft_Z)
        XCTAssertLessThan(zRel, 1e-3, "FFT Z diverges from Python: \(zRel)")

        let gNum = maxAbsDiff(grad, fx.fft_grad)
        var gScale: Float = 0
        for v in fx.fft_grad { gScale = Swift.max(gScale, abs(v)) }
        let gRel = gNum / gScale
        XCTAssertLessThan(gRel, 1e-3, "FFT gradient diverges from Python: \(gRel)")
    }
}
